In [1]:
import numpy as np
np.set_printoptions(suppress=True, precision=10)

phi

In [2]:
#you are given 6 phrases

e1 = ["yo","dude"] # 3 in english
e2 = ["what's","up"]
e3 = ["hey","there","what's","up"]
g1 = ["servus"] # 3 in german
g2 = ["grüß","gott"]
g3 = ["was","geht","ab"]


phrases = [g1,g2,g3,e1,e2,e3]
# 1 for german phrase, -1 for english phrase
# y is the actual label for the phrases e1,e2,e3,g1,g2,g3
y = np.array([1,1,1,-1,-1,-1])

In [5]:
G_words = np.array(["servus", "grüß","gott","digga","was","geht","ab"])
G = G_words.shape[0]

E_words = np.array(["yo","dude","what's","up","hey","there","happening"])
E = E_words.shape[0]

#takes a phrase and returns a one-hot vector with an index for every word
def phi (phrase):
    phi_x = np.zeros((G+E))

    for i in range(len(G_words)):
        phi_x[i] = (G_words[i] in phrase) 
    for i in range(len(E_words)):
        phi_x[i + G] = (E_words[i] in phrase)
    
    return phi_x

phi(["yo","dude"])

array([0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.])

In [6]:
phi(["grüß"])

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
#weight vector for classification
w_phi = np.array([1,1,1,1,1,1,1,-1,-1,-1,-1,-1,-1,-1]) #first G entries are 1 and rest is filled with -1
w_phi

array([ 1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1])

In [8]:
w_phi.T @ phi(["yo","dude"])

-2.0

In [9]:
w_phi.T @ phi(["gott"])

1.0

Kernel

In [10]:
phi(["yo","dude"]).T @ phi(["yo","dude"])

2.0

In [ ]:
phi(["yo","dude"]).T @ phi(["dude","yo"])

2.0

In [11]:
phi(["yo","dude"]).T @ phi(["yo"])

1.0

In [20]:
phi(["dude","was"]).T @ phi(["yo","grüß","gott","digga","was","geht"])

1.0

In [ ]:
#kernel function calculates how many words the phrases share
def k (words1, words2):
    return len(set(words1).intersection(set(words2)))

k(["yo","dude"],["yo","dude"])

2

In [21]:
#Calculate Gram matrix
K = np.zeros((len(phrases), len(phrases)))
for i in range(0, len(phrases)):
    for j in range(0, len(phrases)):
        K[i][j] = (k(phrases[i], phrases[j]))

K

array([[1., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 2., 2.],
       [0., 0., 0., 0., 2., 4.]])

In [22]:
# calculate alpha according to formula in lecture
lam = 0.0001
print(f"y: {y}")
alpha = np.linalg.inv((K + lam * np.identity(len(phrases)))) @ y.T
alpha


y: [ 1  1  1 -1 -1 -1]


array([ 0.99990001  ,  0.4999750012,  0.3333222226, -0.4999750012,
       -0.4999500062, -0.0000249963])

In [ ]:
#predic label
def predict(new_phrase, phrases):
    y = 0
    for i in range(len(phrases)):
        y = y  + alpha[i] * k(new_phrase, phrases[i])
    return y

print(predict(["yo","dude"],phrases))
print(predict(["servus"],phrases))

print(predict(["grüß"],phrases)) #?


-0.9999500024998749
0.9999000099990001
0.49997500124993743
